#pragma once
#include "Kizuri/RHI.h"
#include <vector>
#include <stdint.h>
namespace Kizuri {
struct DeferredMaterial {
  float albedo[3];
  float roughness;
  float metallic;
  RHITexture albedoTex = 0;
};
struct DeferredLight {
  float direction[3];
  float color[3];
  float intensity;
};
struct RenderPointLight {
  float pos[3];
  float color[3];
  float intensity;
  float radius;
  bool castShadow;
  float effectiveSize;
};
struct RenderSpotLight {
  float pos[3];
  float dir[3];
  float color[3];
  float intensity;
  float radius;
  float angle;
  float falloff;
  bool castShadow;
  float effectiveSize;
  int shadowSize;
};
struct RenderDirectionalLight {
  float dir[3];
  float color[3];
  float intensity;
  bool castShadow;
  float effectiveSize;
  int shadowSize;
  int cascades;
  float lambda;
};
struct MainCameraSetup {
  float camPos[3];
  float camFwd[3];
  float camRight[3];
  float camUp[3];
  float fovY;
  float aspect;
  float nearZ;
  float farZ;
};
struct ShadowDrawItem {
  float world[16];
  RHIBuffer vb;
  RHIBuffer ib;
  uint32_t start;
  uint32_t count;
};
class DeferredRenderer {
public:
  DeferredRenderer();
  ~DeferredRenderer();
  bool Initialize(IRHI* rhi, int w, int h, const char* shaderDir);
  void Shutdown();
  bool SetMesh(const float* positions, const float* normals, const float* uvs, size_t vertexCount, const uint32_t* indices, size_t indexCount);
  void SetMaterial(const DeferredMaterial& mat);
  void SetLight(const DeferredLight& light);
  void ClearLights();
  void AddPointLight(const RenderPointLight& light);
  void AddSpotLight(const RenderSpotLight& light);
  void AddDirectionalLight(const RenderDirectionalLight& light);
  void SetMainCamera(const MainCameraSetup& setup);
  void SetShadowDebug(bool debug);
  void SetGrade(float exposure, bool aces);
  void SetBloom(float strength);
  void SetFsr(float scale, float sharpness);
  void SetSsao(bool on, float intensity, float radius);
  void SetFog(bool on, float density, const float color[3]);
  bool Resize(int w, int h);
  void SetViewOffset(float x, float y);
  void Render(const float view[16], const float proj[16], const float camPos[3]);
  void RenderToTexture(const float view[16], const float proj[16], const float camPos[3]);
  void* GetViewportTexture();
  void BeginObjects(const float view[16], const float proj[16]);
  void DrawObject(const float world[16]);
  void DrawObjectEx(const float world[16], RHIBuffer vb, RHIBuffer ib, uint32_t start, uint32_t count, const DeferredMaterial* mat);
  void EndObjectsToTexture(const float camPos[3]);
  void EndObjectsToBackbuffer(const float camPos[3]);
  bool IsReady() const;
private:
  IRHI* rhi;
  int w;
  int h;
  RHIRenderTarget gAlbedo;
  RHIRenderTarget gNormalRough;
  RHIRenderTarget gMetallic;
  RHIRenderTarget gPosition;
  RHIRenderTarget gDepth;
  RHIRenderTarget gViewport;
  RHIBuffer vb;
  RHIBuffer ib;
  RHIConstBuffer geoCB;
  RHIConstBuffer lightCB;
  RHIConstBuffer matCB;
  RHIVertexShader geoVS;
  RHIPixelShader geoPS;
  RHIVertexShader lightVS;
  RHIPixelShader lightPS;
  RHIVertexShader depthVS;
  RHIRenderTarget shadowAtlas;
  RHIRenderTarget shadowCube;
  RHISampler shadowSampler;
  bool shadowsAvailable;
  bool shadowDebug;
  bool shadowMapsValid;
  MainCameraSetup mainCam;
  float shadowCascadeVP[4][16];
  float shadowCascadeSplit[4];
  float shadowCascadeNear[4];
  float shadowCascadeFar[4];
  float shadowCascadeUV[4];
  float shadowCascadeK[4];
  float shadowCascadeSize[4];
  float shadowCascadeLight[4];
  int shadowCascadeActive;
  float shadowSpotVP[4][16];
  float shadowSpotMeta[4][4];
  int shadowSpotActive;
  float shadowPointPos[3];
  float shadowPointFar;
  float shadowPointNear;
  float shadowPointSize;
  int shadowPointLight;
  bool shadowPointActive;
  std::vector<ShadowDrawItem> shadowDraws;
  RHIPixelShader bloomBrightPS;
  RHIPixelShader bloomBlurPS;
  RHIPixelShader bloomAddPS;
  RHIConstBuffer bloomCB;
  RHIRenderTarget gLight;
  RHIRenderTarget bloomA;
  RHIRenderTarget bloomB;
  int bloomW;
  int bloomH;
  float exposure;
  bool acesOn;
  float bloomStrength;
  RHIPixelShader fsrEasuPS;
  RHIPixelShader fsrRcasPS;
  RHIConstBuffer fsrCB;
  RHIRenderTarget fsrA;
  RHIRenderTarget fsrOut;
  int outW;
  int outH;
  float renderScale;
  float fsrSharpness;
  RHIPixelShader ssaoPS;
  RHIPixelShader ssaoBlurPS;
  RHIConstBuffer ssaoCB;
  RHIRenderTarget ssaoA;
  RHIRenderTarget ssaoB;
  int ssaoW;
  int ssaoH;
  bool ssaoOn;
  float ssaoIntensity;
  float ssaoRadius;
  bool ssaoValid;
  bool fogOn;
  float fogDensity;
  float fogColor[3];
  RHIInputLayout layout;
  RHISampler sampler;
  uint32_t indexCount;
  float viewX;
  float viewY;
  bool begun;
  float lastView[16];
  float lastProj[16];
  bool ready;
  DeferredMaterial material;
  DeferredLight light;
  std::vector<RenderPointLight> pointLights;
  std::vector<RenderSpotLight> spotLights;
  std::vector<RenderDirectionalLight> dirLights;
  bool CreateTargets();
  void DestroyTargets();
  void RenderShadowMaps();
  void RenderInternal(const float view[16], const float proj[16], const float camPos[3], bool toTexture);
  void EndInternal(const float camPos[3], bool toTexture);
  DeferredRenderer(const DeferredRenderer&) = delete;
  DeferredRenderer& operator=(const DeferredRenderer&) = delete;
};
}
